In [1]:
import numpy as np

In [2]:
s = 5

In [3]:
s

5

In [4]:
v = np.array([5,2,4])

In [5]:
v

array([5, 2, 4])

In [6]:
m = np.array([[1,2,3],[4,5,6]])

In [7]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(v)

numpy.ndarray

In [9]:
type(m)

numpy.ndarray

In [10]:
m.shape

(2, 3)

In [11]:
v.shape

(3,)

In [12]:
v.reshape(3,1)

array([[5],
       [2],
       [4]])

In [13]:
v.reshape(1,3)

array([[5, 2, 4]])

In [14]:
s_array = np.array([5])

In [15]:
s_array

array([5])

In [16]:
s_array.shape

(1,)

In [17]:
type(s_array)

numpy.ndarray

In [18]:
m1 = np.array([[1,2,3],[5,6,7]])

In [19]:
m1

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
m2 = np.array([[3,4,5],[7,8,9]])

In [21]:
m2

array([[3, 4, 5],
       [7, 8, 9]])

In [22]:
t = np.array([m1,m2])

In [23]:
t

array([[[1, 2, 3],
        [5, 6, 7]],

       [[3, 4, 5],
        [7, 8, 9]]])

In [24]:
t.shape

(2, 2, 3)

In [25]:
t_manual = np.array([[[1, 2, 3],[4 ,5 , 6]],[[5,6,7],[2,3,4]]])

In [26]:
t_manual

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [2, 3, 4]]])

In [27]:
m1 + m2

array([[ 4,  6,  8],
       [12, 14, 16]])

In [28]:
m2-m1

array([[2, 2, 2],
       [2, 2, 2]])

In [29]:
m3 = np.array([[1.33,2.65,3.89],[3.45, 2.32, 5.87],[1.22, 33.44,23.31]])

In [30]:
m3

array([[ 1.33,  2.65,  3.89],
       [ 3.45,  2.32,  5.87],
       [ 1.22, 33.44, 23.31]])

In [31]:
m4 = np.array([[4.55,2.55,34.66],[2.55,7.21,9.23],[36.13,45.26,26.33]])

In [32]:
m4

array([[ 4.55,  2.55, 34.66],
       [ 2.55,  7.21,  9.23],
       [36.13, 45.26, 26.33]])

In [33]:
m3+m4

array([[ 5.88,  5.2 , 38.55],
       [ 6.  ,  9.53, 15.1 ],
       [37.35, 78.7 , 49.64]])

In [34]:
m4-m3

array([[ 3.22, -0.1 , 30.77],
       [-0.9 ,  4.89,  3.36],
       [34.91, 11.82,  3.02]])

In [36]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [37]:
v1+v2

array([6, 6, 6, 6, 6])

In [38]:
v2-v1

array([ 4,  2,  0, -2, -4])

In [39]:
m1

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
m1+1

array([[2, 3, 4],
       [6, 7, 8]])

In [41]:
m1  + np.array([1])

array([[2, 3, 4],
       [6, 7, 8]])

In [42]:
v1

array([1, 2, 3, 4, 5])

In [43]:
v1 +1

array([2, 3, 4, 5, 6])

In [44]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

In [45]:
m1

array([[1, 2, 3],
       [5, 6, 7]])

In [46]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
m1.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [50]:
v1

array([1, 2, 3, 4, 5])

In [51]:
v1.T

array([1, 2, 3, 4, 5])

In [55]:
reshape = v1.reshape(1,5)

In [56]:
reshape

array([[1, 2, 3, 4, 5]])

In [57]:
reshape.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
x = np.array([1,2,4,5])
y = np.array([5,6,7,8])

In [59]:
np.dot(x,y)

85

In [60]:
5*x

array([ 5, 10, 20, 25])

In [61]:
np.dot(5,6)

30

In [62]:
B =np.array([[2,3,4],[5,6,7]])

In [63]:
B

array([[2, 3, 4],
       [5, 6, 7]])

In [64]:
np.dot(B,A)

array([[ 42,  51,  60],
       [ 78,  96, 114]])